server:
  port: 9000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://tts-mysql:3306/susu?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

mybatis:
  check-config-location: false
  scripting-language-driver:
    freemarker:
      template-file:
        base-dir: mappers/
        path-provider:
          includes-package-path: false
          separate-directory-per-mapper: false